## Regenerate src/init.cpp from the .Call entry points defined in src/*.cpp.
##
## Run from the package root:  Rscript tools/make_init.R
##
## Entry points are found two ways: explicit definitions
##   extern "C" SEXP coinclp_foo(SEXP a, SEXP b)
## and the accessor macros defined in coinclp_params.cpp / coinclp_solve.cpp,
## whose arity is fixed by the macro name.

macro_arity <- c(
    CLP_GET_INT = 1L, CLP_GET_DBL = 1L, CLP_GET_LGL = 1L,
    CLP_SET_INT = 2L, CLP_SET_DBL = 2L,
    CLPSOLVE_GET_INT = 1L, CLPSOLVE_SET_INT = 2L
)

sources <- sort(list.files("src", pattern = "[.]cpp$", full.names = TRUE))
sources <- setdiff(sources, "src/init.cpp")

entries <- list()

for (f in sources) {
    txt <- readLines(f, warn = FALSE)

    ## drop #define bodies: the accessor macros contain a signature template
    ## that would otherwise be scanned as a real entry point
    in_define <- FALSE
    keep <- logical(length(txt))
    for (k in seq_along(txt)) {
        line <- txt[k]
        starts <- grepl("^\\s*#\\s*define\\b", line)
        keep[k] <- !(in_define || starts)
        in_define <- (in_define || starts) && grepl("\\\\\\s*$", line)
    }
    code <- txt[keep]

    ## join wrapped signatures so a definition spanning lines still matches
    joined <- paste(code, collapse = "\n")

    ## explicit definitions
    m <- gregexpr('extern "C"[ \n]+SEXP[ \n]+([A-Za-z0-9_]+)[ \n]*\\(([^)]*)\\)',
                  joined, perl = TRUE)
    hits <- regmatches(joined, m)[[1]]
    for (h in hits) {
        name <- sub('^extern "C"[ \n]+SEXP[ \n]+([A-Za-z0-9_]+).*$', "\\1", h)
        args <- sub('^[^(]*\\(', "", sub("\\)$", "", h))
        args <- trimws(args)
        n <- if (identical(args, "void") || !nzchar(args)) 0L
             else length(strsplit(args, ",")[[1]])
        entries[[name]] <- n
    }

    ## macro-generated definitions
    for (mac in names(macro_arity)) {
        pat <- paste0("^", mac, "\\(([A-Za-z0-9_]+),")
        for (line in grep(pat, txt, value = TRUE)) {
            name <- sub(paste0("^", mac, "\\(([A-Za-z0-9_]+),.*$"), "\\1", line)
            entries[[name]] <- macro_arity[[mac]]
        }
    }
}

## drop the two helpers that are not .Call entry points
entries[["coinclp_model"]] <- NULL
entries[["coinclp_options"]] <- NULL

names_sorted <- sort(names(entries))
arity <- unlist(entries[names_sorted])

decl <- sprintf('extern "C" SEXP %s(%s);', names_sorted,
                vapply(arity, function(n) {
                    if (n == 0L) "void" else paste(rep("SEXP", n), collapse = ", ")
                }, ""))

tab <- sprintf('    {"%s", (DL_FUNC) &%s, %d},', names_sorted, names_sorted, arity)

out <- c(
    "/* Generated by tools/make_init.R -- do not edit by hand. */",
    "",
    "#define R_NO_REMAP",
    "#include <R.h>",
    "#include <Rinternals.h>",
    "#include <R_ext/Rdynload.h>",
    "#include <R_ext/Visibility.h>",
    "",
    decl,
    "",
    "static const R_CallMethodDef call_methods[] = {",
    tab,
    "    {NULL, NULL, 0}",
    "};",
    "",
    'extern "C" attribute_visible void R_init_coinclp(DllInfo *dll)',
    "{",
    "    R_registerRoutines(dll, NULL, call_methods, NULL, NULL);",
    "    R_useDynamicSymbols(dll, FALSE);",
    "    R_forceSymbols(dll, TRUE);",
    "}"
)

writeLines(out, "src/init.cpp")
cat("wrote src/init.cpp with", length(names_sorted), "entry points\n")
